version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: husky
    versions:
    - ">= 5.a, < 6"
  - dependency-name: eslint-config-prettier
    versions:
    - 8.2.0
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
